### ISSUE TITLE
Maven package Error

### ISSUE THREAD

**Issue by kyoobin10** [allenday/gcp-popgen#9]
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[66,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[73,90] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[80,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[87,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[95,77] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[102,90] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apa
che.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[INFO] 6 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.819 s
[INFO] Finished at: 2020-03-20T04:27:40Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on pr
oject gcp-popgen: Compilation failure: Compilation failure: 
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[66,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[73,90] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[80,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[87,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[95,77] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apac
he.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/yoobin_kim/test2/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenPr
ocessingAppModule.java:[102,90] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apa
che.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by allenday** [comment]
looks like it might be a java issue, are you using 1.8?

**Comment by kyoobin10** [comment]
Yes,
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

Please check below.
The date for the jar file is yesterday, so we are assuming there are changes in the jar file.

Downloaded from oss.sonatype.org-snapshot: http://oss.sonatype.org/content/repositories/snapshots/com/google/allenday/genomics-dataflow-core/0.0.4-SNAPSHOT/genomics-dataflow-core-0.0.4-20200319.134609-10.jar (157 kB at 20 kB/s)
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ gcp-popgen ---
[INFO] Deleting /home/cheolgon_kang/200318_gcgpoc/gcp-popgen/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ gcp-popgen ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cheolgon_kang/200318_gcgpoc/gcp-popgen/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ gcp-popgen ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /home/cheolgon_kang/200318_gcgpoc/gcp-popgen/target/classes
[INFO] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/cheolgon_kang/200318_gcgpoc/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenProcessingAppModule.java:[66,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apache.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/cheolgon_kang/200318_gcgpoc/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenProcessingAppModule.java:[73,90] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apache.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>
[ERROR] /home/cheolgon_kang/200318_gcgpoc/gcp-popgen/src/main/java/com/google/allenday/popgen/post_processing/FinalizePopGenProcessingAppModule.java:[80,91] incompatible types: java.util.List<java.lang.String> cannot be converted to org.apache.beam.sdk.options.ValueProvider<java.util.List<java.lang.String>>

**Comment by pseveryn** [comment]
@kyoobin10 , thank you for the report! This was broken dependency issue, fixed in https://github.com/allenday/gcp-popgen/pull/10

**Comment by henrychohanwu** [comment]
Hi, I looked at the source code, and I found a discrepancy for dataflow-genomics/core-component and gcp-popgen. And I think this might be related to the build error.

In dataflow-genomics/core-component/src/parts_processing -> line: 32: PrepareAlignNotProcessedFn constructor -> the data type of the second parameter is ValueProvider<List<String>>. However, in gcp-popgen/post_processing -> line 65, it returns the same constructor, but the second parameter is returning List<String>. 

This results in build error in my machine as well. Any idea of how to solve this? thank you!

**Comment by pseveryn** [comment]
@henrychohanwu , 
ValueProvider changes are already in the 0.0.5 core-components version. (https://github.com/allenday/dataflow-genomics/pull/26). Could you specify the error's stacktrace?

**Comment by allenday** [comment]
@henrychohanwu all good now?
